# Generated by Django 4.2.28 on 2026-02-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital_name", models.CharField(max_length=200)),
                ("blood_type_needed", models.CharField(max_length=3)),
                ("quantity", models.IntegerField()),
                ("request_date", models.DateField(auto_now_add=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("blood_type", models.CharField(max_length=3)),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("contact", models.CharField(max_length=100)),
                ("eligibility", models.BooleanField(default=True)),
                ("last_donation", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
